Upgrade commons-lang3 to fix SystemUtils.isJavaVersionAtLeast crashing on Java 10 & 11
org.apache.maven.plugin.PluginExecutionException: Execution default of goal net.orfjackal.retrolambda:retrolambda-maven-plugin:2.5.6-SNAPSHOT:process-main failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.NullPointerException
	at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1626)
	at net.orfjackal.retrolambda.maven.ProcessClassesMojo.validateFork(ProcessClassesMojo.java:146)
	at net.orfjackal.retrolambda.maven.ProcessClassesMojo.execute(ProcessClassesMojo.java:119)
	at net.orfjackal.retrolambda.maven.ProcessMainClassesMojo.execute(ProcessMainClassesMojo.java:17)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more